"""create intake documents table

Revision ID: 41d970c36ef1
Revises: cedf60dae18d
Create Date: 2026-09-11 20:20:21.944390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d970c36ef1'
down_revision: Union[str, Sequence[str], None] = 'cedf60dae18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extraction_status', sa.String(length=50), nullable=False),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('created_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_intake_documents_created_record_id'), 'intake_documents', ['created_record_id'], unique=False)
    op.create_index(op.f('ix_intake_documents_id'), 'intake_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intake_documents_id'), table_name='intake_documents')
    op.drop_index(op.f('ix_intake_documents_created_record_id'), table_name='intake_documents')
    op.drop_table('intake_documents')
    # ### end Alembic commands ###
