"""add verification workflow

Revision ID: c00164a10a62
Revises: 41d970c36ef1
Create Date: 2026-09-12 19:23:07.805235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00164a10a62'
down_revision: Union[str, Sequence[str], None] = '41d970c36ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_requests_id'), 'verification_requests', ['id'], unique=False)
    op.create_index(op.f('ix_verification_requests_record_id'), 'verification_requests', ['record_id'], unique=False)
    op.create_index(op.f('ix_verification_requests_token'), 'verification_requests', ['token'], unique=True)
    op.create_table('proposed_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('verification_request_id', sa.Integer(), nullable=False),
    sa.Column('proposed_fields', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_updates_id'), 'proposed_updates', ['id'], unique=False)
    op.create_index(op.f('ix_proposed_updates_record_id'), 'proposed_updates', ['record_id'], unique=False)
    op.create_index(op.f('ix_proposed_updates_verification_request_id'), 'proposed_updates', ['verification_request_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('verification_request_id', sa.Integer(), nullable=True),
    sa.Column('proposed_update_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposed_update_id'], ['proposed_updates.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_proposed_update_id'), 'audit_events', ['proposed_update_id'], unique=False)
    op.create_index(op.f('ix_audit_events_record_id'), 'audit_events', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_events_verification_request_id'), 'audit_events', ['verification_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_verification_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_record_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_proposed_update_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_proposed_updates_verification_request_id'), table_name='proposed_updates')
    op.drop_index(op.f('ix_proposed_updates_record_id'), table_name='proposed_updates')
    op.drop_index(op.f('ix_proposed_updates_id'), table_name='proposed_updates')
    op.drop_table('proposed_updates')
    op.drop_index(op.f('ix_verification_requests_token'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_record_id'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_id'), table_name='verification_requests')
    op.drop_table('verification_requests')
    # ### end Alembic commands ###
