"""Local filesystem storage for uploaded source documents.

Only the metadata lives in PostgreSQL; the bytes stay on disk in a development
upload directory. This stays deliberately simple - no storage abstraction or
cloud provider until the project actually needs one.
"""

import os
import uuid
from pathlib import Path

# The upload directory sits next to the app package (backend/uploads) and is
# gitignored. Tests point UPLOAD_DIR at a temporary directory instead.
DEFAULT_UPLOAD_DIR = Path(__file__).resolve().parent.parent / "uploads"

# Only PDFs and the common scanned-image formats listed in the blueprint.
# The stored extension comes from this table rather than the uploaded
# filename, so a user cannot choose the extension we write to disk.
ALLOWED_CONTENT_TYPES = {
    "application/pdf": ".pdf",
    "image/png": ".png",
    "image/jpeg": ".jpg",
}

MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024  # 10 MB

# Read in chunks so a large upload is never held in memory all at once.
CHUNK_SIZE_BYTES = 1024 * 1024


def get_upload_dir() -> Path:
    """Return the upload directory, creating it if it does not exist yet."""
    configured = os.getenv("UPLOAD_DIR")
    upload_dir = Path(configured) if configured else DEFAULT_UPLOAD_DIR

    upload_dir.mkdir(parents=True, exist_ok=True)

    return upload_dir


def build_stored_filename(content_type: str) -> str:
    """Generate a unique storage filename that contains no user input."""
    return f"{uuid.uuid4().hex}{ALLOWED_CONTENT_TYPES[content_type]}"


def clean_original_filename(filename: str | None) -> str:
    """Keep a readable original name for display without trusting it as a path.

    Any directory component is dropped so a name like "../../secrets.pdf"
    cannot influence where anything is read from or written to.
    """
    if not filename:
        return "upload"

    # Handle both separators: the browser decides what it sends, not the OS.
    base_name = filename.replace("\\", "/").split("/")[-1].strip()

    if not base_name or base_name in {".", ".."}:
        return "upload"

    return base_name[:255]


def resolve_stored_path(stored_filename: str) -> Path | None:
    """Resolve a stored filename to a path inside the upload directory.

    Returns None if the name would escape the upload directory or the file is
    no longer on disk. Stored names are generated by this module, but the check
    keeps a bad database value from turning into arbitrary filesystem access.
    """
    upload_dir = get_upload_dir().resolve()
    candidate = (upload_dir / stored_filename).resolve()

    if candidate.parent != upload_dir or not candidate.is_file():
        return None

    return candidate
